export default {
  FETCH_SHOWS_REQUEST: `FETCH_SHOWS_REQUEST`,
  FETCH_SHOWS_SUCCESS: `FETCH_SHOWS_SUCCESS`,
  FETCH_SHOWS_FAILURE: `FETCH_SHOWS_FAILURE`,

  FETCH_POSTER_REQUEST: `FETCH_POSTER_REQUEST`,
  FETCH_POSTER_SUCCESS: `FETCH_POSTER_SUCCESS`,
  FETCH_POSTER_FAILURE: `FETCH_POSTER_FAILURE`,
}