export const ACTIONS = {
  FETCH_SHOWS_REQUEST: `FETCH_SHOWS_REQUEST`,
  FETCH_SHOWS_SUCCESS: `FETCH_SHOWS_SUCCESS`,
  FETCH_SHOWS_FAILURE: `FETCH_SHOWS_FAILURE`,

  FETCH_SHOW_REQUEST: `FETCH_SHOW_REQUEST`,
  FETCH_SHOW_SUCCESS: `FETCH_SHOW_SUCCESS`,
  FETCH_SHOW_FAILURE: `FETCH_SHOW_FAILURE`,
}

export const SORTS = {
  TRENDING: `trending`,
  PLAYED: `played`,
  WATCHED: `watched`,
  COLLECTED: `collected`
}

export const API_KEYS = {
  TRAKT: `a7970fc9095e0bca9dc85a9255bc8b9c3d7ac7e120258ab85648ba1a99c89651`,
}