export const ACTIONS = {
  FETCH_SHOWS_REQUEST: `FETCH_SHOWS_REQUEST`,
  FETCH_SHOWS_SUCCESS: `FETCH_SHOWS_SUCCESS`,
  FETCH_SHOWS_FAILURE: `FETCH_SHOWS_FAILURE`,

  FETCH_POSTER_REQUEST: `FETCH_POSTER_REQUEST`,
  FETCH_POSTER_SUCCESS: `FETCH_POSTER_SUCCESS`,
  FETCH_POSTER_FAILURE: `FETCH_POSTER_FAILURE`,
}

export const SORTS = {
  TRENDING: `trending`,
  PLAYED: `played`,
  WATCHED: `watched`,
  COLLECTED: `collected`
}

export const API_KEYS = {
  TRAKT: `a7970fc9095e0bca9dc85a9255bc8b9c3d7ac7e120258ab85648ba1a99c89651`,
  FANART: `20eacf539cc6b09a548f07caede2c27b`,
}