export const ACTIONS = {
  FETCH_SHOWS_REQUEST: 'FETCH_ORDER_REQUEST',
  FETCH_SHOWS_SUCCESS: 'FETCH_SHOWS_SUCCESS',
  FETCH_SHOWS_FAILURE: 'FETCH_ORDER_FAILURE'
}

export const SORTS = {
  TRENDING: `trending`,
  PLAYED: `played`,
  WATCHED: `watched`,
  COLLECTED: `collected`
}